/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    Channel: typeof import('./src/components/Channel.vue')['default']
    ChannelList: typeof import('./src/components/ChannelList.vue')['default']
    ChannelSideBar: typeof import('./src/components/ChannelSideBar.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    ChatMessages: typeof import('./src/components/ChatMessages.vue')['default']
    ChatRoom: typeof import('./src/components/ChatRoom.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FriendList: typeof import('./src/components/FriendList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    ProfileModal: typeof import('./src/components/ProfileModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerSideBar: typeof import('./src/components/ServerSideBar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserProfileModal: typeof import('./src/components/UserProfileModal.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
