/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSetting: typeof import('./src/components/AccountSetting.vue')['default']
    AddChannelDialog: typeof import('./src/components/dialogs/AddChannelDialog.vue')['default']
    AddServerDialog: typeof import('./src/components/dialogs/AddServerDialog.vue')['default']
    AvatarImage: typeof import('./src/components/AvatarImage.vue')['default']
    BottomBar: typeof import('./src/components/BottomBar.vue')['default']
    ChannelList: typeof import('./src/components/ChannelList.vue')['default']
    ChannelRoom: typeof import('./src/components/ChannelRoom.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessages: typeof import('./src/components/ChatMessages.vue')['default']
    ChatWindow: typeof import('./src/components/ChatWindow.vue')['default']
    copy: typeof import('./src/components/DmRoom copy.vue')['default']
    DmRoom: typeof import('./src/components/DmRoom.vue')['default']
    DmRoomList: typeof import('./src/components/DmRoomList.vue')['default']
    DropdownCp: typeof import('./src/components/DropdownCp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FriendList: typeof import('./src/components/FriendList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MemberList: typeof import('./src/components/MemberList.vue')['default']
    PositionMenu: typeof import('./src/components/PositionMenu.vue')['default']
    ProfileModal: typeof import('./src/components/ProfileModal.vue')['default']
    RightClickMenu: typeof import('./src/components/RightClickMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerSideBar: typeof import('./src/components/ServerSideBar.vue')['default']
    SettingDialog: typeof import('./src/components/dialogs/SettingDialog.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
    UserProfileDialog: typeof import('./src/components/dialogs/UserProfileDialog.vue')['default']
    UserProfileSetting: typeof import('./src/components/UserProfileSetting.vue')['default']
    VerticalMenu: typeof import('./src/components/VerticalMenu.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
